# HIDDEN MARKOV MODEL BASELINE FOR MARKET REGIME DETECTION

# Project
# Market Regime Classification Using Hidden Markov Models
# Objective
# Detect hidden market regimes (Bull, Bear, Crisis, Recovery,
# Stable, etc.) from historical NIFTY 50 price data using an
# unsupervised Hidden Markov Model.

# The complete pipeline implemented in this notebook is:

# Market Data

# Data Cleaning

# Feature Engineering

# Feature Scaling

# Gaussian Hidden Markov Model

# Hidden State Prediction

# Regime Statistics

# Transition Analysis

# State Probabilities
       
# Persistence Metrics
        
# Visualization

# Outputs generated by this notebook
# clean_data.csv
# features.csv
# states.csv
# state_probabilities.csv
# transition_matrix.csv
# state_characteristics.csv
# persistence_metrics.csv

# These outputs are used by downstream modules for
# Regime Interpretation
# Trading Strategy Development
# Backtesting
# Dashboard & Visualization

import yfinance as yf
import pandas as pd
import numpy as np
import joblib

from pathlib import Path
from sklearn.preprocessing import StandardScaler
from hmmlearn.hmm import GaussianHMM
from ta.volatility import AverageTrueRange
from ta.momentum import RSIIndicator
from ta.trend import ADXIndicator

import matplotlib.pyplot as plt

ROOT_DIR = Path(__file__).resolve().parents[2]

DATA_DIR = ROOT_DIR / "data"

MODELS_DIR = ROOT_DIR / "models"

DATA_DIR.mkdir(exist_ok=True)

MODELS_DIR.mkdir(exist_ok=True)
# STEP 1 : MARKET DATA COLLECTION
# Objective
# Download historical daily OHLCV (Open, High, Low, Close, Volume) data for the NIFTY 50 index.
# Why NIFTY 50?
#  Represents the Indian equity market.
#  Widely used benchmark index.
#  Contains multiple bull markets, bear markets,
#   corrections, recoveries and periods of high volatility,
#   making it suitable for market regime detection.

# Data Source:Yahoo Finance (via yfinance)
# Time Period:2010 - 2026
# A long time horizon allows the HMM to observe multiple
# economic cycles and learn different hidden market regimes.
# Output
# Raw historical market data.

data = yf.download(
    "^NSEI",
    start="2010-01-01",
    end="2026-01-01",
    auto_adjust=True
)
# Display a few observations to verify that the data has
# been downloaded successfully.
data.head()
# Verify the structure of the downloaded dataset.
# Columns:
# Ensure all required OHLC columns are present.
# Shape:
# Verify the expected number of trading days.
print(data.columns)
print(data.shape)


# ==========================================================
# STEP 2 : DATA CLEANING
# ==========================================================
#
# Objective:
# Convert the raw Yahoo Finance output into a clean dataset
# suitable for feature engineering and HMM training.
#
# Yahoo Finance often returns MultiIndex column names.
# These make downstream processing unnecessarily difficult.
#
# Therefore we:
#  Flatten MultiIndex columns
#  Convert the Date index into a regular column
#  Remove unnecessary metadata
#  Sort observations chronologically
# Maintaining chronological order is critical because Hidden
# Markov Models explicitly model temporal dependencies.
# Output: clean_data.csv
# This serves as the foundation for all subsequent stages of the project.


# Flatten MultiIndex columns
data.columns = data.columns.get_level_values(0)
# Convert Date index to normal column
data = data.reset_index()
# Remove column index name
data.columns.name = None
# Sort by date
data = data.sort_values("Date").reset_index(drop=True)
# Save clean dataset
data.to_csv(DATA_DIR / "clean_data.csv", index=False)
print(data.columns)
print(data.shape)
data.head()

# ========================================================
# Feature Engineering
# ========================================================

# 1. Log Return
data["Log_Return"] = np.log(
    data["Close"] / data["Close"].shift(1)
)

# 2. EWMA Volatility
data["EWMA_Volatility"] = (
    data["Log_Return"]
    .ewm(span=20, adjust=False)
    .std()
)

# 3. ATR (14)

atr = AverageTrueRange(
    high=data["High"],
    low=data["Low"],
    close=data["Close"],
    window=14
)

data["ATR"] = atr.average_true_range()

# 4. RSI (14)

rsi = RSIIndicator(
    close=data["Close"],
    window=14
)

data["RSI"] = rsi.rsi()

# 5. ADX (14)

adx = ADXIndicator(
    high=data["High"],
    low=data["Low"],
    close=data["Close"],
    window=14
)

data["ADX"] = adx.adx()

# Remove NaNs

data = data.dropna().reset_index(drop=True)

features = data[
    [
        "Date",
        "Log_Return",
        "EWMA_Volatility",
        "ATR",
        "RSI",
        "ADX"
    ]
].copy()
features.to_csv(
    DATA_DIR / "features.csv",
    index=False
)
print(features.head())
print(features.shape)
# Standardize all features before HMM training.
# Log returns, volatility, and trading range exist on different numerical scales.
# Standardization prevents features with larger magnitudes from dominating the Gaussian likelihood estimation.
X = features[
    ["Log_Return","EWMA_Volatility","ATR","RSI","ADX"]
]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled[:5])
print(X_scaled.shape)


# Training the Gaussian Hidden Markov Model.
# The HMM assumes that observed market behaviour is generated by a sequence of hidden market regimes.

# Each hidden state is represented by a multivariate Gaussian distribution over the engineered features.
# During training, the Baum-Welch algorithm estimates:
# State transition probabilities
# State emission distributions
#  Initial state probabilities
# without requiring manually labelled market regimes.
hmm_model = GaussianHMM(
    n_components=5,
    covariance_type="full",
    n_iter=500,
    tol=1e-4,
    random_state=42
)

hmm_model.fit(X_scaled)
log_likelihood = hmm_model.score(X_scaled)
# Evaluate the fitted model using the training log-likelihood.
# Higher log-likelihood indicates that the learned model
# explains the observed feature sequence more effectively.
print("Training completed")

print("Number of states:", hmm_model.n_components)
print("Log Likelihood:", log_likelihood)

print("State Means:")
print(hmm_model.means_)
print("\nTransition Matrix:")
print(hmm_model.transmat_)

# from google.colab import drive
# drive.mount('/content/drive')

# Infer the most probable hidden regime for every trading day using the Viterbi algorithm.
# These inferred regimes form the foundation for all downstream analysis including transition analysis, strategy development, and backtesting.

states = hmm_model.predict(X_scaled)

features["State"] = states

print("\nState Counts:")
print(features["State"].value_counts())

print("\nState Statistics:")
print(
    features.groupby("State")[
        [
            "Log_Return",
            "EWMA_Volatility",
            "ATR",
            "RSI",
            "ADX",
        ]
    ].mean()
)

states_df = features[
    ["Date", "State"]
].copy()

states_df.to_csv(
    DATA_DIR / "states.csv",
    index=False
)

print("states.csv saved successfully")
# Compute posterior probabilities for every hidden state.
# Unlike the Viterbi prediction, which assigns only one regime to each observation, posterior probabilities quantify the model's confidence across all possible regimes.
# These probabilities can later be used for confidence analysis, uncertainty estimation, and probabilistic trading strategies.
state_probs = hmm_model.predict_proba(
    X_scaled
)
prob_df = pd.DataFrame(
    state_probs,
    columns=[
        f"State_{i}"
        for i in range(
            hmm_model.n_components
        )
    ]
)
prob_df["Date"] = features["Date"]
prob_df.to_csv(
    DATA_DIR / "state_probabilities.csv",
    index=False
)

print("state_probabilities.csv saved")
# Export the learned transition probability matrix.

# Each element P(i,j) represents the probability of moving from regime i to regime j on the following trading day.
# This matrix captures the persistence and dynamics of the hidden market regimes.
transition_df = pd.DataFrame(
    hmm_model.transmat_
)


transition_df.to_csv(

    DATA_DIR / "transition_matrix.csv",

    index=False

)
print("transition_matrix.csv saved")

# Summarize the statistical properties of each discovered market regime.
# These metrics allow each latent state to be interpreted economically rather than simply being represented by an integer label.
# The resulting table forms the basis for assigning regime names such as Calm Bull, Crisis, or Recovery.

import numpy as np
stats = []
for state in range(
    hmm_model.n_components
):
    state_data = features[
        features["State"] == state
    ]
    mean_return = (
        state_data["Log_Return"]
        .mean()
    )
    volatility = (
        state_data["Log_Return"]
        .std()
    )
    sharpe = (
        mean_return /
        volatility
        if volatility > 0
        else np.nan
    )
    downside = state_data[
        state_data["Log_Return"] < 0
    ]["Log_Return"]
    sortino = (
        mean_return /
        downside.std()
        if len(downside) > 1
        else np.nan
    )
    stats.append({
        "State": state,
        "Frequency": len(state_data),
        "Mean_Return": mean_return,
        "Volatility": volatility,
        "Sharpe_Ratio": sharpe,
        "Sortino_Ratio": sortino
    })
state_characteristics = pd.DataFrame(
    stats
)

state_characteristics.to_csv(

    DATA_DIR / "state_characteristics.csv",

    index=False

)


# Measure regime persistence.
# The diagonal elements of the transition matrix represent the probability of remaining in the same hidden state.
# Expected duration estimates how long a market typically stays within each regime before transitioning.
# Persistent regimes are generally more useful for trading applications than rapidly fluctuating regimes.
persistence = []

for i in range(
    hmm_model.n_components
):

    pii = hmm_model.transmat_[i, i]

    persistence.append({
        "State": i,
        "Persistence": pii,
        "Expected_Duration":
            1/(1-pii)
    })

persistence_df = pd.DataFrame(
    persistence
)

persistence_df.to_csv(

    DATA_DIR / "persistence_metrics.csv",

    index=False

)

joblib.dump(
    hmm_model,
    MODELS_DIR / "hmm_model.pkl"
)

joblib.dump(
    scaler,
    MODELS_DIR / "scaler.pkl"
)
print("Model and scaler saved")

# Visualize the inferred market regimes on the historical
# NIFTY 50 price series.
# Plotting hidden states over time allows us to verify whether the HMM identifies economically meaningful market periods such as crashes, recoveries, and sustained bull markets.
# This qualitative validation complements the statistical evaluation performed earlier.

plot_data = data.copy()

plot_data = plot_data.iloc[-len(states):].copy()

plot_data["State"] = states

plot_data.head()

plt.figure(figsize=(15,6))

for state in sorted(plot_data["State"].unique()):
    mask = plot_data["State"] == state

    plt.scatter(
        plot_data.loc[mask, "Date"],
        plot_data.loc[mask, "Close"],
        s=5,
        label=f"State {state}"
    )

plt.plot(
    plot_data["Date"],
    plot_data["Close"],
    alpha=0.3
)

plt.title("NIFTY 50 Regimes")
plt.xlabel("Date")
plt.ylabel("Close")
plt.legend()
plt.savefig(
    DATA_DIR / "market_regimes.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()
