import yfinance as yf
import pandas as pd
import numpy as np
import joblib

from sklearn.preprocessing import StandardScaler
from hmmlearn.hmm import GaussianHMM
from pathlib import Path

import matplotlib.pyplot as plt

# ROOT = Path(__file__).resolve().parents[2]

ROOT = Path.cwd()
print(ROOT)
# first step for regime detection is to download data. 
#we have selected nifty50 index of past 16 years as our source of data.

data = yf.download(
    "^NSEI",
    start= "2010-01-01",
    end= "2026-01-01",
    auto_adjust=True
)


print(data.head())

print(data.shape)


# Objective:
# Convert the raw Yahoo Finance output into a clean dataset
# suitable for feature engineering and HMM training.
#
# Yahoo Finance often returns MultiIndex column names.
# These make downstream processing unnecessarily difficult.
# Therefore we:
#  Flatten MultiIndex columns
#  Convert the Date index into a regular column
#  Remove unnecessary metadata
#  Sort observations chronologically
# Maintaining chronological order is critical because Hidden
# Markov Models explicitly model temporal dependencies.
# Output: clean_data.csv
# This serves as the foundation for all subsequent stages of the project.

data 

# Flatten MultiIndex columns
data.columns = data.columns.get_level_values(0)
# Convert Date index to normal column
data = data.reset_index()
# Remove column index name
data.columns.name = None
# Sort by date
data = data.sort_values("Date").reset_index(drop=True)
# Save clean dataset
data.to_csv(
    ROOT / "data" / "clean_data.csv"
)
print(data.columns)
print(data.shape)

data.head()


# ========================================================
# Feature Engineering
# ========================================================
# Feature 1 : Log Return
# Log returns measure the day-to-day percentage change in
# market prices while preserving important statistical
# properties such as time additivity.
# They represent the primary measure of market direction
# and are widely used in quantitative finance.
# Calculate log returns
data["Log_Return"] = np.log(
    data["Close"] / data["Close"].shift(1)
)

# Feature 2 : garman klass volatility
# garman klass volatility estimates recent market uncertainty.
# Periods of financial stress typically exhibit sustained
# increases in volatility, making this feature highly
# informative for distinguishing calm and turbulent market regimes
data["gk_volatility"] = np.sqrt(0.5*(np.log(data["High"]/data["Low"]))**2
    -(2*np.log(2)-1) * (np.log(data["Close"]/data["Open"]))**2)


# Range Feature
# Feature 3 : Daily Trading Range
# The normalized high-low range captures intraday price
# movement that may not be fully reflected by closing returns alone.
# This provides additional information about market
# activity and uncertainty within each trading session.

data["Range"] = (
    data["High"] - data["Low"]
) / data["Close"]
# Remove NaN values created by rolling window
data = data.dropna().reset_index(drop=True)


# %%
features = data[[
    "Date",
    "Log_Return",
    "gk_volatility",
    "Range"
]].copy()
print(features.head())
print(features.shape)
# Standardize all features before HMM training.
# Log returns, volatility, and trading range exist on different numerical scales.
# Standardization prevents features with larger magnitudes from dominating the Gaussian likelihood estimation.
# %%

X = features[["Log_Return", "gk_volatility","Range"]]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled[:5])
print(X_scaled.shape)


# %%
# Training the Gaussian Hidden Markov Model.
# The HMM assumes that observed market behaviour is generated by a sequence of hidden market regimes.

# Each hidden state is represented by a multivariate Gaussian distribution over the engineered features.
# During training, the Baum-Welch algorithm estimates:
# State transition probabilities
# State emission distributions
#  Initial state probabilities
# without requiring manually labelled market regimes.
hmm_model = GaussianHMM(
    n_components=5,
    covariance_type="full",
    n_iter=100,
    random_state=42
)

hmm_model.fit(X_scaled)
log_likelihood = hmm_model.score(X_scaled)
# Evaluate the fitted model using the training log-likelihood.
# Higher log-likelihood indicates that the learned model
# explains the observed feature sequence more effectively.
print("Training completed")
print("Number of states:", hmm_model.n_components)
print("Log Likelihood:", log_likelihood)


# %%


joblib.dump(
    hmm_model,
    "hmm_model.pkl"
)

# %%
print("State Means:")
print(hmm_model.means_)
print("\nTransition Matrix:")
print(hmm_model.transmat_)


# %%
features.to_csv(
    ROOT / "data" / "features.csv",
    index=False
)

print("features.csv saved")
# Infer the most probable hidden regime for every trading day using the Viterbi algorithm.
# These inferred regimes form the foundation for all downstream analysis including transition analysis, strategy development, and backtesting.


# %%

# %%
def enforce_min_duration(states, min_duration=10):
    states = np.array(states).copy()
    n = len(states)
    changed = True

    while changed:
        changed = False
        i = 0
        while i < n:
            j = i
            while j < n and states[j] == states[i]:
                j += 1
            run_length = j - i
            if run_length < min_duration:
                if i > 0:
                    fill_value = states[i - 1]
                elif j < n:
                    fill_value = states[j]
                else:
                    fill_value = states[i]
                if fill_value != states[i]:
                    states[i:j] = fill_value
                    changed = True
            i = j
    return states

# %%

# minor update
states = np.array([
    hmm_model.predict(X_scaled[:t+1])[-1] for t in range(len(X_scaled))
])

states = enforce_min_duration(states, min_duration=15)

features["State"] = states 


print("\nState Counts:")
print(features["State"].value_counts())

print("\nState Statistics:")
print(
    features.groupby("State")[
        ["Log_Return", "gk_volatility", "Range"]
    ].mean()
)

states_df = features[
    ["Date", "State"]
].copy()

# %%
states_df.to_csv(
    ROOT /"data" / "states.csv",
    index=False
)
print("states.csv saved successfully")
# Compute posterior probabilities for every hidden state.
# Unlike the Viterbi prediction, which assigns only one regime to each observation, posterior probabilities quantify the model's confidence across all possible regimes.
# These probabilities can later be used for confidence analysis, uncertainty estimation, and probabilistic trading strategies.

# future to condition on, so the last row IS the filtered probability at t.
state_probs = np.array([
    hmm_model.predict_proba(X_scaled[:t+1])[-1]
    for t in range(len(X_scaled))
])

prob_df = pd.DataFrame(
    state_probs,
    columns=[
        f"State_{i}"
        for i in range(
            hmm_model.n_components
        )
    ]
)
prob_df["Date"] = features["Date"]
prob_df.to_csv(
    ROOT / "data" / "state_probabilities.csv",
    index=False
)
print("state_probabilities.csv saved")

# %%
transition_df = pd.DataFrame(
    hmm_model.transmat_
)

transition_df.to_csv(
    ROOT / "data" / "transition_matrix.csv",
    index=False
)
print("transition_matrix.csv saved")

# Summarize the statistical properties of each discovered market regime.
# These metrics allow each latent state to be interpreted economically rather than simply being represented by an integer label.
# The resulting table forms the basis for assigning regime names such as Calm Bull, Crisis, or Recovery.

# %%
import numpy as np

stats = []

# features["GK_Volatility"] = np.sqrt(
#     0.5 * (np.log(features["High"] / features["Low"])) ** 2
#     - (2 * np.log(2) - 1)
#     * (np.log(features["Close"] / features["Open"])) ** 2
# )

for state in range(
    hmm_model.n_components
):

    state_data = features[
        features["State"] == state
    ]

    mean_return = (
        state_data["Log_Return"]
        .mean()
    )

    gk_volatility = state_data["gk_volatility"].mean()

    sharpe = (
        mean_return /
        gk_volatility
        if gk_volatility > 0
        else np.nan
    )

    downside = state_data[
        state_data["Log_Return"] < 0
    ]["Log_Return"]

    sortino = (
        mean_return /
        downside.std()
        if len(downside) > 1
        else np.nan
    )

    stats.append({
        "State": state,
        "Frequency": len(state_data),
        "Mean_Return": mean_return,
        "gk_Volatility": gk_volatility,
        "Sharpe_Ratio": sharpe,
        "Sortino_Ratio": sortino
    })

state_characteristics = pd.DataFrame(
    stats
)
state_characteristics.to_csv(
    ROOT / "data" / "state_characteristics.csv",
    index=False
)
state_characteristics


# Measure regime persistence.
# The diagonal elements of the transition matrix represent the probability of remaining in the same hidden state.
# Expected duration estimates how long a market typically stays within each regime before transitioning.
# Persistent regimes are generally more useful for trading applications than rapidly fluctuating regimes.

# %%
persistence = []

for i in range(
    hmm_model.n_components
):

    pii = hmm_model.transmat_[i, i]

    persistence.append({
        "State": i,
        "Persistence": pii,
        "Expected_Duration":
            1/(1-pii)
    })

persistence_df = pd.DataFrame(
    persistence
)

persistence_df.to_csv(
    ROOT / "data" / "persistence_metrics.csv",
    index=False
)
persistence_df

# %%
import joblib
joblib.dump(
    hmm_model,
    "hmm_model.pkl"
)
joblib.dump(
    scaler,
    "scaler.pkl"
)
print("Model and scaler saved")

# Visualize the inferred market regimes on the historical
# NIFTY 50 price series.
# Plotting hidden states over time allows us to verify whether the HMM identifies economically meaningful market periods such as crashes, recoveries, and sustained bull markets.
# This qualitative validation complements the statistical evaluation performed earlier.

# %%
plot_data = data.copy()

plot_data = plot_data.iloc[-len(states):].copy()

plot_data["State"] = states

plot_data.head()

# %%


plt.figure(figsize=(15,6))

for state in sorted(plot_data["State"].unique()):
    mask = plot_data["State"] == state

    plt.scatter(
        plot_data.loc[mask, "Date"],
        plot_data.loc[mask, "Close"],
        s=5,
        label=f"State {state}"
    )

plt.plot(
    plot_data["Date"],
    plot_data["Close"],
    alpha=0.3
)

plt.title("NIFTY 50 Regimes")
plt.xlabel("Date")
plt.ylabel("Close")
plt.legend()
plt.show()
plt.savefig(
    ROOT / "data" / "plot.png",
    dpi=300,
    bbox_inches="tight"
)